// Example no. 2.: Generating scramble by the config
// Compile command (using GCC): gcc -g main.c -I../../src

#include <stdio.h>

#define SCRAMBLER_IMPLEMENTATION
#include "scrambler.h"

int main(void) {
    scrambleConfig config = scrambleGenerateConfigObject(20, "UDFBLR", " '2");
    char* scramble = scrambleGenerateAsStringByConfig(config);

    printf("Scramble generated by: \"Config\": %s", scramble);

    free(scramble);

    return 0;
}